### ISSUE TITLE
MulJam dataset

### ISSUE THREAD

**Issue by groadabike** [a43992899/MARBLE-Benchmark#13]
Hi, 
Do you know when MulJam2.0 dataset will be available for downloading?
Thank you
Gerardo

**Comment by jhuang448** [comment]
Hi Gerardo,

Many thanks for your interest in our work!
The MulJam preparation code is now available under the **data/muljam-prep** branch. Please run the following:
```
bash ./exp_scripts/download/download_mtg.sh    # download the full MTG-Jamendo dataset
bash ./exp_scripts/preprocess/preprocess_alt.sh    # take the subset from MTG-Jamendo and construct the train/valid/test split
```
Please feel free to contact us if you have any further questions!

Best,
Jiawen

**Comment by groadabike** [comment]
Hi Jiawn, 
Thank you so much for the info.
This is really helpful.

As a comment for possible improvement, you could download just the tracks needed for MulJam and not the whole 156GB, as I understand, MulJam doen't use all the tracks. 
This can help to easily work with the stereo signals if needed in the future.
You already have the full path of the tracks in MTG-Jamendo, therefore you can download them one by one from here https://cdn.freesound.org/mtg-jamendo/raw_30s/audio-low/

Cheers

**Comment by jhuang448** [comment]
Thank you for the suggestion. It is currently done like this because MulJam was created this way, and we agree that downloading the whole MTG-Jamendo is redundant. We will explore options for optimizing the downloading process.
