### ISSUE TITLE
Approaches to Add a New Model

### ISSUE THREAD

**Issue by nicolaus625** [a43992899/MARBLE-Benchmark#6]
Please add the following instructions to the extract part of README

add folder .```/benchmark/models/${model_name}```, and then add ```${model_name}.yaml``` nder the folder. You can refer to hubert and mert if your model is based on transformers with temporal output, otherwise you can refer to  mule or clmr. You may also need to define differnt yaml files and subfolders for different version of your model. 

You also need to include your model load and feature extraction code to  ```extract_${model_name}_feature.py``` under the same folder.

Open the extract.py  file. Add ```from benchmark.models.hubert.extract_hubert_features import main as extract_${model_name}_features_main``` . You may want to comment out the import of other model features to reduce additional dependency of other models.

Add ``'${model_name}':'extract_${model_name}_features_main'```` to NAME_TO_EXTRACT_FEATURES_MAIN in model_constants.py.   If your code is really similar to HUBERT of Music2Vec, you can begin you development with adding your model class to hf_pretrains.py file, and add key-value pairs to NAME_TO_PRETRAIN_CLASS under ```model_constants.py```

Add folder configs/${model_name}/${dataset_name}.yaml. You can copy from other datasets. But you need to change some hyperparameters in the yaml file, such as
- dataset>pretrain_extract>output_dir, 
- dataset>feature_extractor>pretrain 
- dataset>input_dir 
- hp_search>enable: true
- logger>wandb_off

**Comment by blues-green** [comment]
How does the hyperparameter _hp_search_ work  in the code? I can't find any relevant code.
