### ISSUE TITLE
Problems encountered during running download/preprocess scripts

### ISSUE THREAD

**Issue by daisukelab** [a43992899/MARBLE-Benchmark#8]
Hi, thank you for making a valuable benchmark public.
Here, I would like to share some issues I had to fix when installing task datasets.

- exp_scripts/download/download_musdb.sh
I had two issues.
  1. Needed to install musdbconvert: `pip install musdbconvert`
  2. Needed to unzip under the musdb18 folder `unzip ../musdb18.zip -d musdb18`

- exp_scripts/preprocess/preprocess_maestro.sh
MAESTRO -> maestro for the folder name.
  ```diff
  -python benchmark/tasks/MAESTRO/preprocess.py --mode audio --target_sr 24000 --dataset_dir data/MAESTRO/src/maestro-v2.0.0
  -python benchmark/tasks/MAESTRO/preprocess.py --mode label --target_sr 24000 --dataset_dir data/MAESTRO/src/maestro-v2.0.0 --frames_per_second 75 --resume
  +python benchmark/tasks/MAESTRO/preprocess.py --mode audio --target_sr 24000 --dataset_dir data/maestro/maestro-v2.0.0
  +python benchmark/tasks/MAESTRO/preprocess.py --mode label --target_sr 24000 --dataset_dir data/maestro/maestro-v2.0.0 --frames_per_second 75 --resume
  ```

- benchmark/tasks/MAESTRO/preprocess.py
  ```diff
  -sys.path.append(os.path.join(os.path.dirname(os.path.realpath(__file__)), '../../../..'))
  +sys.path.append(os.path.join(os.path.dirname(os.path.realpath(__file__)), '../../..'))
  ```

- exp_scripts/download/download_gs.sh
Unfortunately, this script cannot download zip files.

Thanks again!

**Comment by a43992899** [comment]
Thanks! I am looking into it. Sorry for the issues.

**Comment by a43992899** [comment]
I think the gs download script is fine.

For maestro and musdb, they are still in development. We will update the musdb code from our private repo as soon as possible.

**Comment by daisukelab** [comment]
> I think the gs download script is fine.

Aha, I misunderstood that the downloads (too quick) have failed, and I confirmed now that they are fine.
And I guess the issue is that unzip commands for zip files are missing. The script started downloading audio files now. :)
